# Ref. https://gohugo.io/host-and-deploy/host-on-cloudflare

name = "blog"
compatibility_date = "2025-07-31"

[build]
command = "chmod a+x cf-build.sh && ./cf-build.sh"

[assets]
directory = "./public"
not_found_handling = "404-page"
